'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, ExternalLink, Link2, Loader2, RefreshCw, Send, Share2, ShieldCheck, Trash2 } from 'lucide-react';
import { api } from '@/lib/api';
import type { ApiResponse } from '@/types';
import { MARKETING_BRAND_NAME } from '@/lib/branding';

type Capability = { enabled:boolean; formats?:string[]; notes?:string };
type Connection = { id:string; platform:string; account_name:string|null; account_id:string|null; status:string; last_sync_at:string|null };
type Post = { id:string; platform:string; body:string|null; status:string; scheduled_at:string|null; external_url:string|null; error:string|null; created_at:string };
type ApprovedContent = { id:string; title:string; body:string|null; platform:string|null; version:number; metadata:Record<string,any> };
type Setup = { secretLabel:string; secretPlaceholder:string; secondarySecretLabel?:string; secondarySecretPlaceholder?:string; configLabel?:string; configKey?:string; configPlaceholder?:string; secondaryConfigLabel?:string; secondaryConfigKey?:string; secondaryConfigPlaceholder?:string; warning?:string; consent?:boolean };

const PLATFORM_ORDER = ['instagram','facebook','linkedin','youtube','tiktok','x','threads','pinterest','reddit','bluesky','mastodon','telegram'];
const SETUP:Record<string,Setup> = {
  x:{secretLabel:'OAuth access token',secretPlaceholder:'X access token with post permission'},
  linkedin:{secretLabel:'OAuth access token',secretPlaceholder:'LinkedIn access token',configLabel:'Author URN',configKey:'author_urn',configPlaceholder:'urn:li:person:… or urn:li:organization:…'},
  facebook:{secretLabel:'Page access token',secretPlaceholder:'Facebook Page access token',configLabel:'Page ID',configKey:'page_id',configPlaceholder:'Facebook Page ID'},
  instagram:{secretLabel:'Meta access token',secretPlaceholder:'Token with Instagram publish permissions',configLabel:'Instagram business account ID',configKey:'account_id',configPlaceholder:'Instagram Business/Creator account ID'},
  threads:{secretLabel:'Threads access token',secretPlaceholder:'Threads access token',configLabel:'Threads user ID',configKey:'user_id',configPlaceholder:'Threads user ID'},
  pinterest:{secretLabel:'Pinterest access token',secretPlaceholder:'Pinterest access token',configLabel:'Board ID',configKey:'board_id',configPlaceholder:'Destination board ID'},
  reddit:{secretLabel:'Reddit OAuth access token',secretPlaceholder:'Reddit access token',configLabel:'Subreddit',configKey:'subreddit',configPlaceholder:'e.g. equestrian'},
  youtube:{secretLabel:'Google OAuth access token',secretPlaceholder:'YouTube OAuth access token',configLabel:'Privacy status',configKey:'privacy_status',configPlaceholder:'private, unlisted, or public',warning:'Video visibility follows the privacy state allowed by the connected YouTube account.'},
  tiktok:{secretLabel:'TikTok access token',secretPlaceholder:'Token with Content Posting API permissions',configLabel:'Privacy level',configKey:'privacy_level',configPlaceholder:'A permitted creator privacy option',warning:'Publishing depends on the connected TikTok account and app permissions.',consent:true},
  bluesky:{secretLabel:'Bluesky app password',secretPlaceholder:'Use an app password',secondarySecretLabel:'Handle / identifier',secondarySecretPlaceholder:'name.bsky.social',configLabel:'PDS URL (optional)',configKey:'pds_url',configPlaceholder:'https://bsky.social'},
  mastodon:{secretLabel:'Mastodon access token',secretPlaceholder:'Instance access token with write permission',configLabel:'Instance URL',configKey:'base_url',configPlaceholder:'https://mastodon.social'},
  telegram:{secretLabel:'Telegram bot token',secretPlaceholder:'Bot token',configLabel:'Channel / chat ID',configKey:'chat_id',configPlaceholder:'@channelname or numeric chat ID',secondaryConfigLabel:'Channel username (optional)',secondaryConfigKey:'channel_username',secondaryConfigPlaceholder:'@channelname'},
};
const pretty=(value:string)=>value.split(/[-_]/).map((part)=>part?part[0].toUpperCase()+part.slice(1):part).join(' ');

export default function PublishingPage(){
  const [capabilities,setCapabilities]=useState<Record<string,Capability>>({});
  const [connections,setConnections]=useState<Connection[]>([]); const [posts,setPosts]=useState<Post[]>([]); const [approved,setApproved]=useState<ApprovedContent[]>([]);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [showConnect,setShowConnect]=useState(false);
  const [platform,setPlatform]=useState('instagram'); const [accountName,setAccountName]=useState(''); const [secret,setSecret]=useState(''); const [secondarySecret,setSecondarySecret]=useState(''); const [configValue,setConfigValue]=useState(''); const [secondaryConfigValue,setSecondaryConfigValue]=useState(''); const [consent,setConsent]=useState(false);
  const [connectionId,setConnectionId]=useState(''); const [contentId,setContentId]=useState(''); const [body,setBody]=useState(''); const [mediaUrls,setMediaUrls]=useState(''); const [hashtags,setHashtags]=useState(''); const [scheduledAt,setScheduledAt]=useState('');
  const organizationId=typeof window!=='undefined'?localStorage.getItem('org_id')||'':'';

  const load=useCallback(async()=>{if(!organizationId){setLoading(false);setError('Select a workspace before managing publishing.');return;}setLoading(true);setError(null);try{const [caps,conns,postData,content]=await Promise.all([
    api.get<ApiResponse<Record<string,Capability>>>('/amai/social/capabilities'),api.get<ApiResponse<Connection[]>>('/amai/social/connections'),api.get<ApiResponse<Post[]>>('/amai/social/posts'),api.get<ApiResponse<ApprovedContent[]>>('/content-studio',{params:{status:'approved',type:'social'}}),
  ]);setCapabilities(caps.data||{});setConnections(conns.data||[]);setPosts(postData.data||[]);setApproved(content.data||[]);setConnectionId((current)=>current||conns.data?.find((item)=>item.status==='active')?.id||'');}catch(cause){setError(cause instanceof Error?cause.message:'Publishing could not be loaded.');}finally{setLoading(false);}},[organizationId]);
  useEffect(()=>{void load();},[load]);
  const setup=SETUP[platform]||SETUP.x;
  const selectedConnection=useMemo(()=>connections.find((item)=>item.id===connectionId),[connections,connectionId]);
  const eligible=useMemo(()=>approved.filter((item)=>!selectedConnection||!item.platform||item.platform===selectedConnection.platform),[approved,selectedConnection]);
  const resetConnect=()=>{setAccountName('');setSecret('');setSecondarySecret('');setConfigValue('');setSecondaryConfigValue('');setConsent(false);};
  const selectContent=(id:string)=>{setContentId(id);const item=approved.find((entry)=>entry.id===id);if(!item){setBody('');setMediaUrls('');setHashtags('');return;}const delivery=item.metadata?.delivery&&typeof item.metadata.delivery==='object'?item.metadata.delivery:{};const social=delivery.social&&typeof delivery.social==='object'?delivery.social:{};setBody(String(social.body??item.body??''));const media=Array.isArray(social.media_urls)?social.media_urls:Array.isArray(item.metadata?.media_urls)?item.metadata.media_urls:[];const tags=Array.isArray(social.hashtags)?social.hashtags:Array.isArray(item.metadata?.hashtags)?item.metadata.hashtags:[];setMediaUrls(media.map(String).join('\n'));setHashtags(tags.map(String).join(' '));};

  const connect=async()=>{if(!accountName.trim()||!secret.trim())return;if(platform==='bluesky'&&!secondarySecret.trim())return;if(platform==='tiktok'&&!consent)return;setSaving(true);setError(null);try{const config:Record<string,unknown>={};if(setup.configKey&&configValue.trim())config[setup.configKey]=configValue.trim();if(setup.secondaryConfigKey&&secondaryConfigValue.trim())config[setup.secondaryConfigKey]=secondaryConfigValue.trim();if(platform==='reddit')config.user_agent='AmarktAIMarketing/1.0';if(platform==='tiktok'){config.creator_consent_confirmed=true;config.brand_organic_toggle=true;config.is_aigc=true;}const credentials:Record<string,string>=platform==='telegram'?{bot_token:secret.trim()}:platform==='bluesky'?{identifier:secondarySecret.trim(),app_password:secret.trim()}:{access_token:secret.trim()};const response=await api.post<ApiResponse<Connection>>('/amai/social/connections',{body:{platform,account_name:accountName.trim(),credentials,config}});await api.post(`/amai/social/connections/${response.data.id}/test`,{body:{}});resetConnect();setShowConnect(false);await load();}catch(cause){setError(cause instanceof Error?cause.message:'The account could not be connected.');}finally{setSaving(false);}};
  const test=async(id:string)=>{setBusy(id);setError(null);try{await api.post(`/amai/social/connections/${id}/test`,{body:{}});await load();}catch(cause){setError(cause instanceof Error?cause.message:'Connection test failed.');}finally{setBusy(null);}};
  const remove=async(id:string)=>{if(!confirm('Remove this publishing connection?'))return;setBusy(id);try{await api.delete(`/amai/social/connections/${id}`);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Connection removal failed.');}finally{setBusy(null);}};
  const createPost=async(publishNow:boolean)=>{if(!connectionId||!contentId||!body.trim())return;setSaving(true);setError(null);try{await api.post('/amai/social/posts',{body:{connection_id:connectionId,content_id:contentId,body:body.trim(),media_urls:mediaUrls.split(/[\n,]/).map((v)=>v.trim()).filter(Boolean),hashtags:hashtags.split(/[\s,]/).map((v)=>v.trim()).filter(Boolean).map((v)=>v.startsWith('#')?v:`#${v}`),scheduled_at:publishNow?undefined:scheduledAt||undefined,publish_now:publishNow}});setContentId('');setBody('');setMediaUrls('');setHashtags('');setScheduledAt('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Publishing request failed.');}finally{setSaving(false);}};
  const retry=async(id:string)=>{setBusy(id);try{await api.post(`/amai/social/posts/${id}/publish`,{body:{}});await load();}catch(cause){setError(cause instanceof Error?cause.message:'Publishing retry failed.');}finally{setBusy(null);}};
  const canConnect=Boolean(accountName.trim()&&secret.trim()&&(platform!=='bluesky'||secondarySecret.trim())&&(platform!=='tiktok'||consent));

  return <div className="space-y-6">
    <section className="rounded-[24px] border border-[#d9e1e7] bg-[linear-gradient(135deg,#fff_0%,#f3f8fb_65%,#eff7f4_100%)] p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#2e6da4]">Publishing</p><h1 className="mt-1 font-serif text-3xl font-semibold text-[#172c3d]">Publish approved content</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#61727d]">Connect your social accounts and publish only the exact content versions approved in {MARKETING_BRAND_NAME}.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-[#d6d0c8] bg-white px-4 py-2.5 text-sm font-bold text-[#315166]"><RefreshCw className="h-4 w-4"/>Refresh</button><button type="button" onClick={()=>setShowConnect(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#2e6da4] px-4 py-2.5 text-sm font-bold text-white"><Link2 className="h-4 w-4"/>Connect account</button></div></div></section>
    {error&&<div className="flex items-start gap-3 rounded-xl border border-[#efc7c0] bg-[#fff5f2] p-4 text-sm text-[#963e35]"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>{error}</div>}
    <section className="rounded-2xl border border-[#cfe2dd] bg-[#f1f8f6] p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-[#348d82]"/><div><p className="text-sm font-bold text-[#294b45]">Approval protection</p><p className="mt-1 text-xs leading-5 text-[#61727d]">Publishing remains tied to an owner-approved Content Library version. A scheduled or retried post does not become a new unapproved version.</p></div></div></section>

    {showConnect&&<section className="ep-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#172c3d]">Connect a social account</h2><p className="mt-1 text-xs text-[#718089]">Credentials are encrypted before storage and are not displayed after saving.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-[#405968]">Platform<select value={platform} onChange={(e)=>{setPlatform(e.target.value);resetConnect();}} className="ep-input mt-2 h-11 px-3">{PLATFORM_ORDER.map((item)=><option key={item} value={item}>{pretty(item)}</option>)}</select></label><label className="text-sm font-semibold text-[#405968]">Account name<input value={accountName} onChange={(e)=>setAccountName(e.target.value)} className="ep-input mt-2 h-11 px-3" placeholder="Brand account"/></label><label className="text-sm font-semibold text-[#405968]">{setup.secretLabel}<input type="password" autoComplete="new-password" value={secret} onChange={(e)=>setSecret(e.target.value)} className="ep-input mt-2 h-11 px-3" placeholder={setup.secretPlaceholder}/></label>{setup.secondarySecretLabel&&<label className="text-sm font-semibold text-[#405968]">{setup.secondarySecretLabel}<input value={secondarySecret} onChange={(e)=>setSecondarySecret(e.target.value)} className="ep-input mt-2 h-11 px-3" placeholder={setup.secondarySecretPlaceholder}/></label>}{setup.configLabel&&<label className="text-sm font-semibold text-[#405968]">{setup.configLabel}<input value={configValue} onChange={(e)=>setConfigValue(e.target.value)} className="ep-input mt-2 h-11 px-3" placeholder={setup.configPlaceholder}/></label>}{setup.secondaryConfigLabel&&<label className="text-sm font-semibold text-[#405968]">{setup.secondaryConfigLabel}<input value={secondaryConfigValue} onChange={(e)=>setSecondaryConfigValue(e.target.value)} className="ep-input mt-2 h-11 px-3" placeholder={setup.secondaryConfigPlaceholder}/></label>}</div>{setup.warning&&<p className="mt-4 rounded-xl border border-[#ead39a] bg-[#fff9ea] p-3 text-xs text-[#75531c]">{setup.warning}</p>}{setup.consent&&<label className="mt-4 flex items-start gap-3 rounded-xl border border-[#e3ded7] bg-[#faf8f5] p-3 text-sm text-[#405968]"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} className="mt-1"/><span>I confirm this creator/account has chosen to connect for publishing and the account permissions allow the requested use.</span></label>}<div className="mt-5 flex gap-2"><button type="button" disabled={saving||!canConnect} onClick={()=>void connect()} className="rounded-xl bg-[#2e6da4] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?'Connecting…':'Save and test'}</button><button type="button" onClick={()=>{resetConnect();setShowConnect(false);}} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-[#61727d]">Cancel</button></div></section>}

    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold text-[#172c3d]">Connected accounts</h2><span className="text-xs text-[#7a8992]">{connections.length} connected records</span></div>{loading?<div className="flex justify-center py-12"><Loader2 className="h-7 w-7 animate-spin text-[#2e6da4]"/></div>:connections.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{connections.map((connection)=><article key={connection.id} className="ep-card p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-[#edf4f9] p-2 text-[#2e6da4]"><Share2 className="h-4 w-4"/></span><div className="min-w-0"><p className="font-bold capitalize text-[#314958]">{pretty(connection.platform)}</p><p className="truncate text-xs text-[#7a8992]">{connection.account_name||connection.account_id||'Connected account'}</p></div></div><span className={connection.status==='active'?'text-xs font-bold text-[#348d82]':'text-xs font-bold text-[#a44b43]'}>{connection.status}</span></div><p className="mt-3 text-[11px] text-[#87939a]">{connection.last_sync_at?`Checked ${new Date(connection.last_sync_at).toLocaleString()}`:'Not tested yet'}</p><div className="mt-4 flex gap-2"><button type="button" onClick={()=>void test(connection.id)} className="inline-flex items-center gap-1 rounded-lg border border-[#ded8cf] px-2.5 py-1.5 text-xs font-semibold text-[#405968]">{busy===connection.id?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<RefreshCw className="h-3.5 w-3.5"/>}Test</button><button type="button" aria-label="Remove connection" onClick={()=>void remove(connection.id)} className="ml-auto rounded-lg p-1.5 text-[#87939a] hover:bg-[#fff2ef] hover:text-[#a44b43]"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>:<div className="rounded-2xl border border-dashed border-[#d8d1c8] bg-[#faf8f5] p-8 text-center text-sm text-[#75838b]">No social accounts are connected yet.</div>}</section>

    <section className="ep-card p-5 sm:p-6"><h2 className="text-lg font-bold text-[#172c3d]">Prepare a post</h2><p className="mt-1 text-sm text-[#687983]">Select an active connection and an approved social-content version.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-[#405968]">Connection<select value={connectionId} onChange={(e)=>{setConnectionId(e.target.value);selectContent('');}} className="ep-input mt-2 h-11 px-3"><option value="">Select an active account</option>{connections.filter((item)=>item.status==='active').map((item)=><option key={item.id} value={item.id}>{pretty(item.platform)} — {item.account_name||'account'}</option>)}</select></label><label className="text-sm font-semibold text-[#405968]">Schedule time<input type="datetime-local" value={scheduledAt} onChange={(e)=>setScheduledAt(e.target.value)} className="ep-input mt-2 h-11 px-3"/></label><label className="text-sm font-semibold text-[#405968] md:col-span-2">Approved content<select value={contentId} onChange={(e)=>selectContent(e.target.value)} className="ep-input mt-2 h-11 px-3"><option value="">Select approved social content</option>{eligible.map((item)=><option key={item.id} value={item.id}>{item.title} · v{item.version}{item.platform?` · ${pretty(item.platform)}`:''}</option>)}</select></label><label className="text-sm font-semibold text-[#405968] md:col-span-2">Approved post body<textarea rows={5} value={body} readOnly className="ep-input mt-2 p-3" placeholder="Select approved content"/></label><label className="text-sm font-semibold text-[#405968]">Approved media<textarea rows={3} value={mediaUrls} readOnly className="ep-input mt-2 p-3"/></label><label className="text-sm font-semibold text-[#405968]">Approved hashtags<textarea rows={3} value={hashtags} readOnly className="ep-input mt-2 p-3"/></label></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={saving||!connectionId||!contentId||!body.trim()} onClick={()=>void createPost(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#2e6da4] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4"/>Publish approved version</button><button type="button" disabled={saving||!connectionId||!contentId||!body.trim()||!scheduledAt} onClick={()=>void createPost(false)} className="rounded-xl border border-[#d6d0c8] bg-white px-4 py-2.5 text-sm font-bold text-[#315166] disabled:opacity-50">Schedule</button></div></section>

    <section className="ep-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e5dfd7] px-5 py-4"><h2 className="font-bold text-[#172c3d]">Publishing history</h2><span className="text-xs text-[#7a8992]">{posts.length} total</span></div>{posts.length?<div className="divide-y divide-[#e7e1d9]">{posts.slice(0,50).map((post)=><article key={post.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#314958]">{post.body||'Post'}</p><p className="mt-1 text-xs text-[#7a8992]">{pretty(post.platform)}{post.scheduled_at?` · ${new Date(post.scheduled_at).toLocaleString()}`:''}</p>{post.error&&<p className="mt-1 text-xs text-[#a44b43]">{post.error}</p>}</div><div className="flex items-center gap-2"><span className="rounded-full bg-[#f3f0eb] px-3 py-1 text-xs font-semibold capitalize text-[#526a79]">{post.status}</span>{['draft','failed'].includes(post.status)&&<button type="button" onClick={()=>void retry(post.id)} className="rounded-lg bg-[#2e6da4] px-3 py-1.5 text-xs font-bold text-white">Retry</button>}{post.external_url&&<a href={post.external_url} target="_blank" rel="noreferrer" className="text-[#2e6da4]" aria-label="Open published post"><ExternalLink className="h-4 w-4"/></a>}</div></article>)}</div>:<div className="p-10 text-center text-sm text-[#75838b]">No publishing activity yet.</div>}</section>
  </div>;
}
