'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  AlertCircle, ArrowLeft, CheckCircle2, Clock3, Copy, GitCompareArrows, History,
  Loader2, RotateCcw, Save, Send, ShieldCheck, Sparkles, WandSparkles, X,
} from 'lucide-react';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth.store';
import type { ApiResponse } from '@/types';

type ContentItem={id:string;title:string;body:string|null;type:string;platform:string|null;status:string;workflow_state:string;version:number;word_count:number;quality_score:number;metadata:Record<string,any>;updated_at:string};
type ContentVersion={id:string;version:number;body?:string|null;change_summary:string|null;created_at:string};
type QualityCheck={id:string;check_type:string;score:number;passed:boolean;issues:Array<{message:string;severity:string}>};
function statusClass(status:string){if(['approved','published'].includes(status))return 'ep-status-success';if(['rejected'].includes(status))return 'ep-status-danger';return 'ep-status-warning';}

export default function ContentEditorPage(){
  const params=useParams<{id:string}>();const router=useRouter();const {currentOrganization}=useAuthStore();const orgId=currentOrganization?.id||'';
  const [content,setContent]=useState<ContentItem|null>(null);const [versions,setVersions]=useState<ContentVersion[]>([]);const [checks,setChecks]=useState<QualityCheck[]>([]);const [title,setTitle]=useState('');const [body,setBody]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [action,setAction]=useState<string|null>(null);const [dirty,setDirty]=useState(false);const [error,setError]=useState<string|null>(null);const [revisionInstruction,setRevisionInstruction]=useState('');const [reviewComment,setReviewComment]=useState('');const [compareVersion,setCompareVersion]=useState<ContentVersion|null>(null);const initialised=useRef(false);const editorRef=useRef<HTMLTextAreaElement>(null);const revisionAttempt=useRef<{fingerprint:string;key:string}|null>(null);

  const load=useCallback(async()=>{if(!params.id||!orgId){setLoading(false);return;}try{const [itemResponse,versionResponse,qualityResponse]=await Promise.all([api.get<ApiResponse<ContentItem>>(`/content-studio/${params.id}`,{params:{organization_id:orgId}}),api.get<ApiResponse<ContentVersion[]>>(`/content-studio/${params.id}/versions`,{params:{organization_id:orgId}}),api.get<ApiResponse<QualityCheck[]>>(`/content-studio/${params.id}/quality-checks`,{params:{organization_id:orgId}})]);setContent(itemResponse.data);setVersions(versionResponse.data||[]);setChecks(qualityResponse.data||[]);if(!initialised.current){setTitle(itemResponse.data.title);setBody(itemResponse.data.body||'');initialised.current=true;}}catch(caught){setError(caught instanceof Error?caught.message:'This content item could not be loaded.');}finally{setLoading(false);}},[orgId,params.id]);
  useEffect(()=>{void load();},[load]);

  const save=useCallback(async()=>{if(!content||!dirty||saving)return;setSaving(true);setError(null);try{const response=await api.put<ApiResponse<ContentItem>>(`/content-studio/${content.id}`,{body:{organization_id:orgId,title:title.trim()||content.title,body}});setContent(response.data);setDirty(false);const versionResponse=await api.get<ApiResponse<ContentVersion[]>>(`/content-studio/${content.id}/versions`,{params:{organization_id:orgId}});setVersions(versionResponse.data||[]);}catch(caught){setError(caught instanceof Error?caught.message:'Autosave failed.');}finally{setSaving(false);}},[body,content,dirty,orgId,saving,title]);
  useEffect(()=>{if(!dirty)return;const timer=window.setTimeout(()=>void save(),1200);return()=>window.clearTimeout(timer);},[dirty,save]);

  const runAction=async(name:string,fn:()=>Promise<unknown>)=>{setAction(name);setError(null);try{await save();await fn();await load();}catch(caught){setError(caught instanceof Error?caught.message:`${name} failed.`);}finally{setAction(null);}};
  const restore=(version:number)=>runAction('restore',async()=>{const response=await api.post<ApiResponse<ContentItem>>(`/content-studio/${params.id}/versions/${version}/restore`,{body:{organization_id:orgId}});setContent(response.data);setTitle(response.data.title);setBody(response.data.body||'');setDirty(false);});
  const revise=async()=>{const instruction=revisionInstruction.trim();if(!instruction||!content)return;const editor=editorRef.current;const selectedText=editor&&editor.selectionStart!==editor.selectionEnd?body.slice(editor.selectionStart,editor.selectionEnd):'';const fingerprint=JSON.stringify({instruction,selectedText,version:content.version});if(!revisionAttempt.current||revisionAttempt.current.fingerprint!==fingerprint)revisionAttempt.current={fingerprint,key:crypto.randomUUID()};setAction('revise');setError(null);try{await save();const response=await api.post<ApiResponse<ContentItem>>(`/content-studio/${content.id}/revise`,{body:{organization_id:orgId,instruction,selected_text:selectedText||undefined,idempotency_key:`content-revision:${revisionAttempt.current.key}`}});revisionAttempt.current=null;setRevisionInstruction('');setContent(response.data);setTitle(response.data.title);setBody(response.data.body||'');setDirty(false);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Revision failed.');}finally{setAction(null);}};
  const duplicate=()=>runAction('duplicate',async()=>{const response=await api.post<ApiResponse<ContentItem>>(`/content-studio/${params.id}/duplicate`,{body:{organization_id:orgId}});router.push(`/content-studio/${response.data.id}`);});

  if(loading)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[var(--ep-blue)]"/></div>;
  if(!content)return <div className="ep-status-danger rounded-xl border p-5">{error||'Content not found.'}</div>;

  const latestChecks=Object.values(checks.reduce<Record<string,QualityCheck>>((acc,check)=>{if(!acc[check.check_type])acc[check.check_type]=check;return acc;},{}));
  const qualityPassed=latestChecks.length>0&&latestChecks.every((check)=>check.passed);

  return <div className="space-y-6">
    <button type="button" onClick={()=>router.back()} className="inline-flex items-center gap-2 text-sm font-extrabold text-[var(--ep-blue)]"><ArrowLeft className="h-4 w-4"/> Back to Content Studio</button>
    <header className="ep-panel p-6 sm:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`${statusClass(content.status)} rounded-full border px-2.5 py-1 text-[10px] font-extrabold uppercase`}>{content.status}</span><span className="rounded-full bg-[var(--ep-surface-subtle)] px-2.5 py-1 text-[10px] font-extrabold text-[var(--ep-text-muted)]">Version {content.version}</span></div><h1 className="ep-page-title mt-3">Content editor</h1><p className="ep-page-copy mt-2 text-sm">{content.type}{content.platform?` · ${content.platform}`:''} · {content.word_count} words · {content.workflow_state.replaceAll('_',' ')}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void save()} disabled={!dirty||saving} className="ep-button-secondary px-3 py-2.5 text-sm">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>} {saving?'Saving':'Save'}</button><button type="button" onClick={()=>void runAction('quality',()=>api.post(`/content-studio/${content.id}/quality-check`,{body:{organization_id:orgId}}))} disabled={Boolean(action)} className="ep-button-secondary px-3 py-2.5 text-sm"><Sparkles className="h-4 w-4"/> Check quality</button><button type="button" onClick={()=>void duplicate()} disabled={Boolean(action)} className="ep-button-secondary px-3 py-2.5 text-sm"><Copy className="h-4 w-4"/> Duplicate</button>{content.status==='draft'&&<button type="button" onClick={()=>void runAction('submit',()=>api.post(`/content-studio/${content.id}/submit`,{body:{organization_id:orgId}}))} disabled={!qualityPassed||Boolean(action)} title={!qualityPassed?'Pass quality checks first':'Submit this exact version'} className="ep-button-primary px-3 py-2.5 text-sm"><Send className="h-4 w-4"/> Submit for review</button>}{content.status==='review'&&<button type="button" onClick={()=>void runAction('approve',()=>api.post(`/content-studio/${content.id}/approve`,{body:{organization_id:orgId,comments:reviewComment.trim()||'Owner approved in Content Studio'}}))} disabled={Boolean(action)} className="ep-button-primary px-3 py-2.5 text-sm"><ShieldCheck className="h-4 w-4"/> Approve exact version</button>}</div></div></header>
    {error&&<div className="ep-status-danger flex items-start gap-3 rounded-xl border px-4 py-3 text-sm"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><span className="flex-1">{error}</span><button type="button" onClick={()=>setError(null)}><X className="h-4 w-4"/></button></div>}

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <main className="space-y-5">
        {content.status==='review'&&<section className="ep-status-warning rounded-xl border p-4"><label className="block text-xs font-extrabold">Owner review comment<input value={reviewComment} onChange={(event)=>setReviewComment(event.target.value)} placeholder="Approval note or exact change requested" className="ep-input mt-2 min-h-10 px-3 text-sm font-normal"/></label><div className="mt-3 flex gap-2"><button type="button" onClick={()=>void runAction('changes',()=>api.post(`/content-studio/${content.id}/request-changes`,{body:{organization_id:orgId,comments:reviewComment}}))} disabled={!reviewComment.trim()||Boolean(action)} className="ep-button-secondary px-3 py-2 text-xs"><RotateCcw className="h-3.5 w-3.5"/> Request changes</button><button type="button" onClick={()=>void runAction('reject',()=>api.post(`/content-studio/${content.id}/reject`,{body:{organization_id:orgId,comments:reviewComment}}))} disabled={!reviewComment.trim()||Boolean(action)} className="rounded-lg border border-[#e5b9b4] bg-white px-3 py-2 text-xs font-bold text-[var(--ep-danger)] hover:bg-[var(--ep-danger-soft)]">Reject</button></div></section>}

        <section className="ep-card p-5 sm:p-6"><label className="block"><span className="mb-1.5 block text-xs font-extrabold text-[var(--ep-text-muted)]">Title</span><input value={title} onChange={(event)=>{setTitle(event.target.value);setDirty(true);}} className="ep-input min-h-11 px-3 text-base font-extrabold"/></label><label className="mt-4 block"><span className="mb-1.5 block text-xs font-extrabold text-[var(--ep-text-muted)]">Content</span><textarea ref={editorRef} value={body} onChange={(event)=>{setBody(event.target.value);setDirty(true);}} rows={26} className="ep-input w-full resize-y px-4 py-3 font-mono text-sm leading-7"/></label><div className="mt-3 flex items-center gap-2 text-xs text-[var(--ep-text-soft)]">{saving?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Clock3 className="h-3.5 w-3.5"/>}{dirty?'Unsaved changes':'All changes saved as a restorable version'}</div></section>

        <section className="ep-card p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-[var(--ep-blue-soft)] p-2.5 text-[var(--ep-blue)]"><WandSparkles className="h-4 w-4"/></span><div className="flex-1"><h2 className="font-extrabold text-[var(--ep-navy)]">Targeted revision</h2><p className="mt-1 text-xs leading-5 text-[var(--ep-text-muted)]">Select text above to revise only that section, or leave nothing selected to revise the asset. Other campaign assets remain untouched.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={revisionInstruction} onChange={(event)=>setRevisionInstruction(event.target.value)} placeholder="Make the opening more specific and concise" className="ep-input min-h-10 flex-1 px-3 text-sm"/><button type="button" onClick={()=>void revise()} disabled={!revisionInstruction.trim()||Boolean(action)} className="ep-button-primary px-4 py-2 text-sm">{action==='revise'?<Loader2 className="h-4 w-4 animate-spin"/>:<WandSparkles className="h-4 w-4"/>} Revise</button></div></div></div></section>

        {compareVersion&&<section className="ep-card p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold text-[var(--ep-navy)]">Version {compareVersion.version} compared with current</h2><button type="button" onClick={()=>setCompareVersion(null)} className="rounded-lg p-2 text-[var(--ep-text-soft)] hover:bg-[var(--ep-surface-subtle)]"><X className="h-4 w-4"/></button></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><VersionText label={`Version ${compareVersion.version}`} value={compareVersion.body||'No content'}/><VersionText label="Current" value={body}/></div></section>}
      </main>

      <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start">
        <section className="ep-card p-5"><h2 className="flex items-center gap-2 font-extrabold text-[var(--ep-navy)]"><CheckCircle2 className={`h-4 w-4 ${qualityPassed?'text-[var(--ep-success)]':'text-[var(--ep-warning)]'}`}/> Quality gates</h2>{latestChecks.length===0?<p className="mt-3 text-xs leading-5 text-[var(--ep-text-muted)]">Run the quality checks before submitting this version.</p>:<div className="mt-3 space-y-2">{latestChecks.map((check)=><div key={check.check_type} className="rounded-xl bg-[var(--ep-page)] p-3"><div className="flex justify-between gap-3 text-xs"><span className="font-extrabold capitalize text-[var(--ep-navy)]">{check.check_type.replaceAll('_',' ')}</span><span className={check.passed?'font-bold text-[var(--ep-success)]':'font-bold text-[var(--ep-warning)]'}>{Math.round(check.score)}%</span></div>{check.issues.slice(0,2).map((issue)=><p key={issue.message} className="mt-1 text-[11px] leading-4 text-[var(--ep-text-muted)]">{issue.message}</p>)}</div>)}</div>}</section>

        <section className="ep-card p-5"><h2 className="flex items-center gap-2 font-extrabold text-[var(--ep-navy)]"><History className="h-4 w-4 text-[var(--ep-blue)]"/> Version history</h2>{versions.length===0?<p className="mt-3 text-xs text-[var(--ep-text-muted)]">No previous versions.</p>:<div className="mt-3 space-y-2">{versions.map((version)=><div key={version.id||version.version} className="rounded-xl border border-[var(--ep-border)] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold text-[var(--ep-navy)]">Version {version.version}</p><p className="mt-1 text-[11px] leading-4 text-[var(--ep-text-muted)]">{version.change_summary||'Saved edit'} · {new Date(version.created_at).toLocaleString()}</p></div><div className="flex gap-1"><button type="button" onClick={()=>setCompareVersion(version)} className="rounded-lg p-2 text-[var(--ep-text-muted)] hover:bg-[var(--ep-blue-soft)] hover:text-[var(--ep-blue)]" title="Compare"><GitCompareArrows className="h-3.5 w-3.5"/></button>{version.version!==content.version&&<button type="button" onClick={()=>void restore(version.version)} disabled={Boolean(action)} className="rounded-lg p-2 text-[var(--ep-text-muted)] hover:bg-[var(--ep-blue-soft)] hover:text-[var(--ep-blue)]" title="Restore"><RotateCcw className="h-3.5 w-3.5"/></button>}</div></div></div>)}</div>}</section>
      </aside>
    </div>
  </div>;
}

function VersionText({label,value}:{label:string;value:string}){return <div><p className="mb-1 text-[10px] font-extrabold uppercase tracking-wide text-[var(--ep-text-soft)]">{label}</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--ep-page)] p-3 text-xs leading-5 text-[var(--ep-text-muted)]">{value}</pre></div>;}
