'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Coins, Gauge, Loader2, RefreshCw, ShieldAlert, ShieldCheck, WalletCards } from 'lucide-react';
import { api } from '@/lib/api';
import type { ApiResponse } from '@/types';

type ControlCentre = {
  policy:{ operating_mode:string; emergency_stop:boolean; daily_generation_credit_limit:number; per_action_credit_limit:number; daily_ad_budget_pence:number; per_campaign_ad_limit_pence:number; approval_credit_threshold:number; approval_ad_threshold_pence:number; allowed_channels:string[]; require_approval_for_new_channel:boolean; require_approval_for_new_audience:boolean; require_approval_for_price_claims:boolean; timezone:string; version:number };
  runtime:{ state:string; can_execute_autonomously:boolean; in_active_window:boolean };
  wallet:{ available_credits:number; reserved_credits:number; lifetime_spent_credits:number };
  today:{ generation_credits_used:number; generation_credits_remaining:number; daily_generation_credit_limit:number; daily_ad_budget_pence:number; recorded_ad_spend_pence:number };
  connections:Array<{category:string;total:number;active:number;healthy:number}>;
  decisions:Array<{id:string;title:string;channel:string;status:string;requested_credits:number;requested_ad_spend_pence:number;created_at:string}>;
};
const gbp=(pence:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(pence)||0)/100);

export default function AutomationSafetyPage(){
  const [data,setData]=useState<ControlCentre|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await api.get<ApiResponse<ControlCentre>>('/relaunch-control');if(!response.data)throw new Error('Safety status is unavailable.');setData(response.data);}catch(cause){setError(cause instanceof Error?cause.message:'Safety status could not be loaded.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const pending=useMemo(()=>data?.decisions.filter((item)=>item.status==='pending')||[],[data]);
  const connected=useMemo(()=>data?.connections.reduce((sum,row)=>sum+row.active,0)||0,[data]);
  const healthy=useMemo(()=>data?.connections.reduce((sum,row)=>sum+row.healthy,0)||0,[data]);
  if(loading&&!data)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#2e6da4]"/></div>;
  if(!data)return <div className="rounded-xl border border-[#efc7c0] bg-[#fff5f2] p-5 text-sm text-[#963e35]"><AlertCircle className="mb-2 h-5 w-5"/>{error||'Safety status unavailable.'}</div>;
  const stopped=data.policy.emergency_stop;
  return <div className="space-y-6">
    <section className="rounded-[24px] border border-[#d9e1e7] bg-[linear-gradient(135deg,#fff_0%,#f4f8fb_70%,#f3f8f6_100%)] p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#2e6da4]"><ShieldCheck className="h-4 w-4"/>Automation & Safety</div><h1 className="mt-2 font-serif text-3xl font-semibold text-[#172c3d]">Workspace protection</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#61727d]">See the real operating mode, safety stop, budgets, credit limits and approvals governing this workspace.</p></div><button type="button" onClick={()=>void load()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#d6d0c8] bg-white px-4 py-2.5 text-sm font-bold text-[#315166]"><RefreshCw className="h-4 w-4"/>Refresh</button></div></section>
    {error&&<div className="rounded-xl border border-[#efc7c0] bg-[#fff5f2] p-4 text-sm text-[#963e35]">{error}</div>}
    <section className={stopped?'rounded-2xl border border-[#ead39a] bg-[#fff9ea] p-5':'rounded-2xl border border-[#cfe2dd] bg-[#f1f8f6] p-5'}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3">{stopped?<ShieldAlert className="mt-0.5 h-6 w-6 text-[#8b641e]"/>:<ShieldCheck className="mt-0.5 h-6 w-6 text-[#348d82]"/>}<div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#718089]">Current state</p><h2 className="mt-1 text-xl font-bold capitalize text-[#172c3d]">{stopped?'Emergency stop on':data.runtime.state.replace(/_/g,' ')}</h2><p className="mt-1 text-sm text-[#61727d]">Operating mode: <strong className="capitalize text-[#314958]">{data.policy.operating_mode}</strong>. {stopped?'Execution remains blocked while the safety stop is on.':'Configured limits and approval rules remain in force.'}</p></div></div><span className={stopped?'rounded-full bg-[#f8e8bd] px-3 py-1.5 text-xs font-bold text-[#75531c]':'rounded-full bg-[#dcefe9] px-3 py-1.5 text-xs font-bold text-[#286d62]'}>{stopped?'Protected / paused':'Active'}</span></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      {label:'Credits available',value:data.wallet.available_credits.toLocaleString('en-GB'),detail:`${data.wallet.reserved_credits.toLocaleString('en-GB')} reserved`,icon:Coins},
      {label:'Credits used today',value:data.today.generation_credits_used.toLocaleString('en-GB'),detail:`Limit ${data.today.daily_generation_credit_limit.toLocaleString('en-GB')}`,icon:Gauge},
      {label:'Daily ad budget',value:gbp(data.today.daily_ad_budget_pence),detail:`Recorded ${gbp(data.today.recorded_ad_spend_pence)}`,icon:WalletCards},
      {label:'Healthy connections',value:`${healthy}/${connected}`,detail:'Active connection health',icon:ShieldCheck},
    ].map(({label,value,detail,icon:Icon})=><article key={label} className="ep-card p-5"><Icon className="h-5 w-5 text-[#2e6da4]"/><p className="mt-4 text-xs font-bold uppercase tracking-[0.12em] text-[#7a8992]">{label}</p><p className="mt-1 text-2xl font-bold text-[#172c3d]">{value}</p><p className="mt-1 text-xs text-[#87939a]">{detail}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="ep-card p-5 sm:p-6"><h2 className="text-lg font-bold text-[#172c3d]">Policy limits</h2><p className="mt-1 text-xs text-[#7a8992]">Policy version {data.policy.version} · {data.policy.timezone}</p><dl className="mt-5 space-y-3 text-sm">{[
      ['Per generation action',`${data.policy.per_action_credit_limit.toLocaleString('en-GB')} credits`],['Daily generation limit',`${data.policy.daily_generation_credit_limit.toLocaleString('en-GB')} credits`],['Per campaign ad limit',gbp(data.policy.per_campaign_ad_limit_pence)],['Approval above',`${data.policy.approval_credit_threshold.toLocaleString('en-GB')} credits / ${gbp(data.policy.approval_ad_threshold_pence)}`],
    ].map(([label,value])=><div key={label} className="flex items-center justify-between gap-4 rounded-xl bg-[#f6f4f0] px-4 py-3"><dt className="text-[#61727d]">{label}</dt><dd className="text-right font-bold text-[#314958]">{value}</dd></div>)}</dl><div className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#7a8992]">Allowed channels</p><div className="mt-2 flex flex-wrap gap-2">{(data.policy.allowed_channels||[]).map((channel)=><span key={channel} className="rounded-full bg-[#edf4f9] px-3 py-1 text-xs font-semibold capitalize text-[#315f7d]">{channel}</span>)}</div></div></section>
      <section className="ep-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-[#172c3d]">Pending approvals</h2><p className="mt-1 text-xs text-[#7a8992]">Actions awaiting an owner decision</p></div><span className="rounded-full bg-[#f3f0eb] px-3 py-1 text-xs font-bold text-[#526a79]">{pending.length}</span></div>{pending.length?<div className="mt-5 space-y-3">{pending.slice(0,8).map((item)=><article key={item.id} className="rounded-xl border border-[#e3ded7] bg-[#faf8f5] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#314958]">{item.title}</p><p className="mt-1 text-xs capitalize text-[#7a8992]">{item.channel}</p></div><span className="text-xs font-semibold text-[#8b641e]">Pending</span></div><p className="mt-2 text-xs text-[#61727d]">Requested: {item.requested_credits.toLocaleString('en-GB')} credits{item.requested_ad_spend_pence?` · ${gbp(item.requested_ad_spend_pence)}`:''}</p></article>)}</div>:<div className="mt-5 flex items-center gap-3 rounded-xl bg-[#f1f8f6] p-4 text-sm text-[#3d665e]"><CheckCircle2 className="h-5 w-5 text-[#348d82]"/>No actions are waiting for approval.</div>}</section></div>
    <section className="rounded-2xl border border-[#d8e2e8] bg-[#f4f8fb] p-4 text-sm leading-6 text-[#526a79]"><strong className="text-[#314958]">Safety changes are intentionally not exposed on this client screen during acceptance.</strong> The current state remains visible and fail-closed; no button here can accidentally release the emergency stop or switch operating mode.</section>
  </div>;
}
