'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import {
  AlertCircle, CheckCircle2, Clock3, Eye, FileText, Filter, Globe2, Loader2,
  Mail, Search, Sparkles, Trash2, X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth.store';
import type { ApiResponse } from '@/types';

type ContentItem={id:string;title:string;type:string;platform:string|null;status:string;word_count:number;quality_score:number;ai_generated:boolean;created_at:string;updated_at:string};
const statuses=['all','draft','review','approved','scheduled','published','rejected','archived'];
const typeLabels:Record<string,string>={blog:'Blog post',article:'Article',landing_page:'Landing page',sales_page:'Sales page',email:'Email',newsletter:'Newsletter',social:'Social post',product_desc:'Product description',press_release:'Press release'};
function statusClass(status:string){if(['approved','published'].includes(status))return 'ep-status-success';if(['rejected'].includes(status))return 'ep-status-danger';if(['review','scheduled'].includes(status))return 'ep-status-warning';return 'bg-[var(--ep-surface-subtle)] text-[var(--ep-text-muted)] border-[var(--ep-border)]';}
function typeIcon(type:string):LucideIcon{if(['email','newsletter'].includes(type))return Mail;if(['landing_page','social'].includes(type))return Globe2;return FileText;}

export default function ContentStudioPage(){
  const {currentOrganization}=useAuthStore(); const orgId=currentOrganization?.id||'';
  const [items,setItems]=useState<ContentItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(''); const [typeFilter,setTypeFilter]=useState('all'); const [statusFilter,setStatusFilter]=useState('all'); const [busy,setBusy]=useState<string|null>(null);
  const fetchItems=useCallback(async()=>{if(!orgId){setLoading(false);return;}setLoading(true);setError(null);try{const params:Record<string,string>={organization_id:orgId};if(typeFilter!=='all')params.type=typeFilter;if(statusFilter!=='all')params.status=statusFilter;const response=await api.get<ApiResponse<ContentItem[]>>('/content-studio',{params});setItems(response.data||[]);}catch(caught){setError(caught instanceof Error?caught.message:'Content could not be loaded.');}finally{setLoading(false);}},[orgId,statusFilter,typeFilter]);
  useEffect(()=>{void fetchItems();},[fetchItems]);
  const handleDelete=async(id:string)=>{if(!confirm('Delete this content item?'))return;setBusy(id);try{await api.delete(`/content-studio/${id}`,{params:{organization_id:orgId}});await fetchItems();}catch(caught){setError(caught instanceof Error?caught.message:'The content item could not be deleted.');}finally{setBusy(null);}};
  const filtered=useMemo(()=>items.filter((item)=>!search.trim()||item.title.toLowerCase().includes(search.trim().toLowerCase())),[items,search]);
  const types=useMemo(()=>['all',...Array.from(new Set(items.map((item)=>item.type)))],[items]);
  const stats={total:items.length,drafts:items.filter((item)=>item.status==='draft').length,review:items.filter((item)=>item.status==='review').length,approved:items.filter((item)=>item.status==='approved').length,published:items.filter((item)=>item.status==='published').length};
  const statCards:{label:string;count:number;Icon:LucideIcon}[]=[
    {label:'All content',count:stats.total,Icon:FileText},
    {label:'Drafts',count:stats.drafts,Icon:FileText},
    {label:'Owner review',count:stats.review,Icon:Clock3},
    {label:'Approved',count:stats.approved,Icon:CheckCircle2},
    {label:'Published',count:stats.published,Icon:Globe2},
  ];

  return <div className="space-y-6">
    <header className="ep-panel p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-3xl"><p className="ep-section-label">Content Studio</p><h1 className="ep-page-title mt-2">Create, review, version and govern campaign content.</h1><p className="ep-page-copy mt-3 text-sm leading-6 sm:text-base">The library is the customer workflow for drafts, quality review, exact-version approval, scheduled content and published work.</p></div><div className="flex flex-wrap gap-2"><Link href="/approvals" className="ep-button-secondary px-4 py-2.5 text-sm"><Clock3 className="h-4 w-4"/> Owner approvals</Link><Link href="/content-studio/generate" className="ep-button-primary px-4 py-2.5 text-sm"><Sparkles className="h-4 w-4"/> Create content</Link></div></div></header>
    {error&&<div className="ep-status-danger flex items-start gap-3 rounded-xl border px-4 py-3 text-sm"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><span className="flex-1">{error}</span><button type="button" onClick={()=>setError(null)}><X className="h-4 w-4"/></button></div>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-5">{statCards.map(({label,count,Icon})=><article key={label} className="ep-card p-4 sm:p-5"><Icon className="h-4 w-4 text-[var(--ep-blue)]"/><p className="mt-3 text-2xl font-extrabold text-[var(--ep-navy)]">{count}</p><p className="mt-1 text-[11px] font-bold text-[var(--ep-text-muted)]">{label}</p></article>)}</section>
    <section className="ep-card p-3"><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><label className="relative flex-1"><span className="sr-only">Search content</span><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--ep-text-soft)]"/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search content title" className="ep-input min-h-10 pl-10 pr-3 text-sm"/></label><div className="flex max-w-full items-center gap-1.5 overflow-x-auto"><Filter className="h-4 w-4 shrink-0 text-[var(--ep-text-soft)]"/>{statuses.map((status)=><button type="button" key={status} onClick={()=>setStatusFilter(status)} className={statusFilter===status?'shrink-0 rounded-lg bg-[var(--ep-navy)] px-3 py-2 text-xs font-bold capitalize text-white':'shrink-0 rounded-lg px-3 py-2 text-xs font-bold capitalize text-[var(--ep-text-muted)] hover:bg-[var(--ep-blue-soft)]'}>{status}</button>)}</div><select value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value)} className="ep-input min-h-10 w-full px-3 text-xs font-bold sm:w-auto">{types.map((type)=><option key={type} value={type}>{type==='all'?'All formats':typeLabels[type]||type}</option>)}</select></div></section>
    {loading?<div className="ep-card flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-[var(--ep-blue)]"/></div>:filtered.length===0?<section className="ep-card py-16 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--ep-blue-soft)] text-[var(--ep-blue)]"><FileText className="h-7 w-7"/></div><h2 className="mt-5 text-lg font-extrabold text-[var(--ep-navy)]">No content in this view</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--ep-text-muted)]">Create governed content or change the current status/type filters.</p><Link href="/content-studio/generate" className="ep-button-primary mt-5 px-4 py-2.5 text-sm"><Sparkles className="h-4 w-4"/> Create content</Link></section>:<section className="space-y-3">{filtered.map((item)=>{const Icon=typeIcon(item.type);return <article key={item.id} className="ep-card p-5 transition hover:border-[#9fb4c8]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--ep-blue-soft)] text-[var(--ep-blue)]"><Icon className="h-5 w-5"/></span><div className="min-w-0"><h3 className="truncate font-extrabold text-[var(--ep-navy)]">{item.title}</h3><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[var(--ep-text-muted)]"><span>{typeLabels[item.type]||item.type}</span>{item.platform&&<span>{item.platform}</span>}<span>{Number(item.word_count||0).toLocaleString()} words</span>{item.ai_generated&&<span>AI-assisted</span>}<span>Updated {new Date(item.updated_at).toLocaleDateString('en-ZA')}</span></div></div></div><div className="flex shrink-0 items-center gap-2"><span className={`${statusClass(item.status)} rounded-full border px-2.5 py-1 text-[10px] font-extrabold uppercase`}>{item.status}</span>{item.quality_score>0&&<span className="text-xs font-bold text-[var(--ep-text-muted)]">Quality {Math.round(item.quality_score)}%</span>}<Link href={`/content-studio/${item.id}`} className="rounded-lg p-2 text-[var(--ep-text-muted)] hover:bg-[var(--ep-blue-soft)] hover:text-[var(--ep-blue)]" aria-label={`Open ${item.title}`}><Eye className="h-4 w-4"/></Link><button type="button" disabled={busy===item.id} onClick={()=>void handleDelete(item.id)} className="rounded-lg p-2 text-[var(--ep-text-soft)] hover:bg-[var(--ep-danger-soft)] hover:text-[var(--ep-danger)]" aria-label={`Delete ${item.title}`}>{busy===item.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}</button></div></div></article>;})}</section>}
  </div>;
}
