'use client';

import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, BarChart3, Globe2, Loader2, Save, Search, Sparkles, X } from 'lucide-react';
import { api } from '@/lib/api';
import type { ApiResponse } from '@/types';

type Tab = 'keywords' | 'audit';
interface SeoKeyword { id:string; keyword:string; search_volume:number; difficulty:number; intent:string|null }
interface SeoAudit { id:string; url:string; score:number; issues:Array<{type:string;severity:string;message:string}>; suggestions:string[]; created_at:string }
type ResearchKeyword = { keyword:string; search_volume:number; difficulty:number; intent:string };
const inputClass='ep-input min-h-11 px-3 py-2.5 text-sm';

export default function SeoPage(){
  const [tab,setTab]=useState<Tab>('keywords');
  const [keywords,setKeywords]=useState<SeoKeyword[]>([]); const [audits,setAudits]=useState<SeoAudit[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [seed,setSeed]=useState(''); const [researching,setResearching]=useState(false); const [results,setResults]=useState<ResearchKeyword[]>([]); const [saving,setSaving]=useState(false);
  const [auditUrl,setAuditUrl]=useState(''); const [auditing,setAuditing]=useState(false);
  const orgId=typeof window!=='undefined'?localStorage.getItem('org_id')||'':'';

  const load=useCallback(async()=>{if(!orgId){setLoading(false);return;}setLoading(true);setError(null);try{const [keywordResponse,auditResponse]=await Promise.all([api.get<ApiResponse<SeoKeyword[]>>('/seo/keywords',{params:{organization_id:orgId}}),api.get<ApiResponse<SeoAudit[]>>('/seo/audits',{params:{organization_id:orgId}})]);setKeywords(keywordResponse.data||[]);setAudits(auditResponse.data||[]);}catch(caught){setError(caught instanceof Error?caught.message:'SEO intelligence could not be loaded.');}finally{setLoading(false);}},[orgId]);
  useEffect(()=>{void load();},[load]);

  const research=async()=>{if(!seed.trim()||!orgId)return;setResearching(true);setError(null);try{const response=await api.post<ApiResponse<ResearchKeyword[]>>('/seo/keywords/research',{body:{organization_id:orgId,seed:seed.trim(),count:15}});setResults(response.data||[]);}catch(caught){setError(caught instanceof Error?caught.message:'Keyword research failed.');}finally{setResearching(false);}};
  const saveKeywords=async()=>{if(!results.length||!orgId)return;setSaving(true);setError(null);try{await api.post('/seo/keywords/save',{body:{organization_id:orgId,keywords:results}});setResults([]);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Keywords could not be saved.');}finally{setSaving(false);}};
  const audit=async()=>{if(!auditUrl.trim()||!orgId)return;setAuditing(true);setError(null);try{await api.post('/seo/audit',{body:{organization_id:orgId,url:auditUrl.trim()}});setAuditUrl('');await load();}catch(caught){setError(caught instanceof Error?caught.message:'Site audit failed.');}finally{setAuditing(false);}};

  return <div className="space-y-6">
    <header className="ep-panel p-6 sm:p-8"><p className="ep-section-label">Research & Intelligence · SEO</p><h1 className="ep-page-title mt-2">Turn search evidence into better campaign and content decisions.</h1><p className="ep-page-copy mt-3 max-w-3xl text-sm leading-6 sm:text-base">Research keywords, keep useful search terms and audit public pages. Values shown here come from the configured SEO capability; unavailable data stays unavailable rather than being fabricated.</p></header>
    {error&&<div className="ep-status-danger flex items-start gap-3 rounded-xl border px-4 py-3 text-sm"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><span className="flex-1">{error}</span><button type="button" onClick={()=>setError(null)}><X className="h-4 w-4"/></button></div>}
    <div className="ep-card flex gap-1 p-1.5">{([['keywords','Keyword research',Search],['audit','Site audits',Globe2]] as const).map(([value,label,Icon])=><button type="button" key={value} onClick={()=>setTab(value)} className={tab===value?'flex items-center gap-2 rounded-lg bg-[var(--ep-navy)] px-4 py-2.5 text-sm font-extrabold text-white':'flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-bold text-[var(--ep-text-muted)] hover:bg-[var(--ep-blue-soft)]'}><Icon className="h-4 w-4"/>{label}</button>)}</div>

    {tab==='keywords'?<div className="space-y-5">
      <section className="ep-card p-5 sm:p-6"><p className="ep-section-label">Discover</p><h2 className="mt-1 text-lg font-extrabold text-[var(--ep-navy)]">Research a topic</h2><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={seed} onChange={(event)=>setSeed(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter')void research();}} placeholder="Enter a product, service or search topic" className={`${inputClass} min-w-0 flex-1`}/><button type="button" onClick={()=>void research()} disabled={researching||!seed.trim()} className="ep-button-primary px-4 py-2.5 text-sm">{researching?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>} Research</button></div>{results.length>0&&<div className="mt-5"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-extrabold text-[var(--ep-navy)]">Research results</p><button type="button" onClick={()=>void saveKeywords()} disabled={saving} className="ep-button-secondary px-3 py-2 text-xs">{saving?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Save className="h-3.5 w-3.5"/>} Save all</button></div><div className="overflow-x-auto rounded-xl border border-[var(--ep-border)]"><table className="min-w-full text-left text-sm"><thead className="bg-[var(--ep-surface-subtle)] text-xs text-[var(--ep-text-muted)]"><tr><th className="px-4 py-3">Keyword</th><th className="px-4 py-3">Volume</th><th className="px-4 py-3">Difficulty</th><th className="px-4 py-3">Intent</th></tr></thead><tbody className="divide-y divide-[var(--ep-border)]">{results.map((keyword)=><tr key={keyword.keyword}><td className="px-4 py-3 font-bold text-[var(--ep-navy)]">{keyword.keyword}</td><td className="px-4 py-3 text-[var(--ep-text-muted)]">{Number(keyword.search_volume||0).toLocaleString()}</td><td className="px-4 py-3 text-[var(--ep-text-muted)]">{Number(keyword.difficulty||0).toFixed(0)}</td><td className="px-4 py-3 capitalize text-[var(--ep-text-muted)]">{keyword.intent||'—'}</td></tr>)}</tbody></table></div></div>}</section>
      <section className="ep-card overflow-hidden"><div className="border-b border-[var(--ep-border)] px-5 py-4"><p className="ep-section-label">Saved evidence</p><h2 className="mt-1 text-lg font-extrabold text-[var(--ep-navy)]">Keywords</h2></div>{loading?<div className="flex justify-center py-14"><Loader2 className="h-6 w-6 animate-spin text-[var(--ep-blue)]"/></div>:keywords.length===0?<div className="py-14 text-center text-sm text-[var(--ep-text-muted)]">No saved keywords yet.</div>:<div className="divide-y divide-[var(--ep-border)]">{keywords.map((keyword)=><div key={keyword.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><span className="font-extrabold text-[var(--ep-navy)]">{keyword.keyword}</span><span className="text-xs text-[var(--ep-text-muted)]">{Number(keyword.search_volume||0).toLocaleString()} / mo</span><span className="text-xs text-[var(--ep-text-muted)]">Difficulty {Math.round(Number(keyword.difficulty||0))}</span><span className="text-xs capitalize text-[var(--ep-text-muted)]">{keyword.intent||'—'}</span></div>)}</div>}</section>
    </div>:<div className="space-y-5">
      <section className="ep-card p-5 sm:p-6"><p className="ep-section-label">Public page audit</p><h2 className="mt-1 text-lg font-extrabold text-[var(--ep-navy)]">Audit a URL</h2><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="url" value={auditUrl} onChange={(event)=>setAuditUrl(event.target.value)} placeholder="https://example.com/page" className={`${inputClass} min-w-0 flex-1`}/><button type="button" onClick={()=>void audit()} disabled={auditing||!auditUrl.trim()} className="ep-button-primary px-4 py-2.5 text-sm">{auditing?<Loader2 className="h-4 w-4 animate-spin"/>:<Globe2 className="h-4 w-4"/>} Run audit</button></div></section>
      {audits.length===0?<div className="ep-card py-14 text-center"><BarChart3 className="mx-auto h-8 w-8 text-[var(--ep-text-soft)]"/><p className="mt-3 text-sm font-semibold text-[var(--ep-text-muted)]">No site audits yet.</p></div>:<div className="space-y-4">{audits.map((entry)=><article key={entry.id} className="ep-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-all font-extrabold text-[var(--ep-navy)]">{entry.url}</h3><p className="mt-1 text-xs text-[var(--ep-text-soft)]">{new Date(entry.created_at).toLocaleString()}</p></div><div className="rounded-xl bg-[var(--ep-blue-soft)] px-4 py-3 text-center"><p className="text-[10px] font-bold uppercase text-[var(--ep-text-muted)]">SEO score</p><p className="mt-1 text-2xl font-extrabold text-[var(--ep-navy)]">{Math.round(Number(entry.score||0))}</p></div></div>{entry.issues?.length>0&&<div className="mt-5 space-y-2">{entry.issues.slice(0,8).map((issue,index)=><div key={`${issue.message}-${index}`} className="rounded-xl bg-[var(--ep-surface-subtle)] px-4 py-3"><div className="flex items-center gap-2"><span className="text-[10px] font-extrabold uppercase text-[var(--ep-blue)]">{issue.severity}</span><p className="text-sm font-semibold text-[var(--ep-navy)]">{issue.message}</p></div></div>)}</div>}{entry.suggestions?.length>0&&<div className="mt-5"><p className="text-xs font-extrabold text-[var(--ep-text-muted)]">Recommended improvements</p><ul className="mt-2 space-y-2">{entry.suggestions.slice(0,8).map((suggestion)=><li key={suggestion} className="text-sm leading-6 text-[var(--ep-text-muted)]">• {suggestion}</li>)}</ul></div>}</article>)}</div>}
    </div>}
  </div>;
}
